In [6]:
import pandas as pd

df = pd.read_json("data/results_prwp_batch1.jsonl", lines=True)
# df = pd.read_json("data/results_refugee_batch1.jsonl", lines=True)
df

,snapshot_id,image_path,source_label,llm_output,raw_output,usage,cost,error
0,document_10069312_table_006.png,data/prwp_batch1/document_10069312_table_006.png,PRWP,{'visible_text_label': 'Table 7: Intra Africa ...,"{\n ""visible_text_label"": ""Table 7: Intra Afr...","{'input_tokens': 26214, 'input_tokens_details'...","{'input_tokens': 26214, 'output_tokens': 157, ...",None
1,document_11958451_figure_002.png,data/prwp_batch1/document_11958451_figure_002.png,PRWP,{'visible_text_label': 'Figure 2: Russia: Infl...,"{\n ""visible_text_label"": ""Figure 2: Russia: ...","{'input_tokens': 49095, 'input_tokens_details'...","{'input_tokens': 49095, 'output_tokens': 157, ...",None
2,document_11958451_figure_021.png,data/prwp_batch1/document_11958451_figure_021.png,PRWP,{'visible_text_label': 'Figure 20. Average oil...,"{\n ""visible_text_label"": ""Figure 20. Average...","{'input_tokens': 26427, 'input_tokens_details'...","{'input_tokens': 26427, 'output_tokens': 130, ...",None
3,document_700615_table_004.png,data/prwp_batch1/document_700615_table_004.png,PRWP,{'visible_text_label': 'Table A-2 - Dependent ...,"{\n ""visible_text_label"": ""Table A-2 - Depend...","{'input_tokens': 26186, 'input_tokens_details'...","{'input_tokens': 26186, 'output_tokens': 127, ...",None
4,document_11958451_table_001.png,data/prwp_batch1/document_11958451_table_001.png,PRWP,{'visible_text_label': 'Table 2. Consolidated ...,"```json\n{\n ""visible_text_label"": ""Table 2. ...","{'input_tokens': 49095, 'input_tokens_details'...","{'input_tokens': 49095, 'output_tokens': 145, ...",None
...,...,...,...,...,...,...,...,...
392,document_11867889_figure_012.png,data/prwp_batch1/document_11867889_figure_012.png,PRWP,{'visible_text_label': 'Figure 14. Evolution o...,"{\n ""visible_text_label"": ""Figure 14. Evoluti...","{'input_tokens': 48961, 'input_tokens_details'...","{'input_tokens': 48961, 'output_tokens': 146, ...",None
393,document_6731296_table_002.png,data/prwp_batch1/document_6731296_table_002.png,PRWP,{'visible_text_label': 'Table 3 Compensation f...,"```json\n{\n ""visible_text_label"": ""Table 3\n...","{'input_tokens': 26387, 'input_tokens_details'...","{'input_tokens': 26387, 'output_tokens': 141, ...",None
394,document_10002285_table_000.png,data/prwp_batch1/document_10002285_table_000.png,PRWP,{'visible_text_label': 'Table 1 Summary statis...,"```json\n{\n ""visible_text_label"": ""Table 1 S...","{'input_tokens': 48892, 'input_tokens_details'...","{'input_tokens': 48892, 'output_tokens': 138, ...",None
395,document_700561_figure_004.png,data/prwp_batch1/document_700561_figure_004.png,PRWP,{'visible_text_label': 'FREQUENCY DISTRIBUTION...,"{\n ""visible_text_label"": ""FREQUENCY DISTRIBU...","{'input_tokens': 26383, 'input_tokens_details'...","{'input_tokens': 26383, 'output_tokens': 132, ...",None
396,document_1689472_figure_001.png,data/prwp_batch1/document_1689472_figure_001.png,PRWP,{'visible_text_label': 'Figure 2: Frequency Di...,"{\n ""visible_text_label"": ""Figure 2: Frequenc...","{'input_tokens': 37955, 'input_tokens_details'...","{'input_tokens': 37955, 'output_tokens': 120, ...",None

In [9]:
df.loc[29]

snapshot_id                         document_438376_table_000.png
image_path         data/prwp_batch1/document_438376_table_000.png
source_label                                                 PRWP
llm_output      {'visible_text_label': 'Table 1a Water dischar...
raw_output      {\n  "visible_text_label": "Table 1a Water dis...
usage           {'input_tokens': 37635, 'input_tokens_details'...
cost            {'input_tokens': 37635, 'output_tokens': 164, ...
error                                                        None
Name: 29, dtype: object

In [2]:
pd.json_normalize(df["cost"])["total_cost_usd"].sum()

np.float64(0.20881199999999994)

In [4]:
pd.json_normalize(df["llm_output"]).loc[0, "short_description"]

'The table lists various consultancy assignments related to urban development projects, including estimated costs and selection methods for hiring coordinators and conducting assessments.'

In [5]:
pd.json_normalize(df["llm_output"])

,visible_text_label,data_modality,topic_domain,population,geographic_scope,temporal_aspect,measurement_units,short_description
0,Consultancy Assignments with Selection Methods...,administrative counts,urban development,unclear,West Bank and Gaza,unclear,USD ($000),The table lists various consultancy assignment...
1,"Figure 1: Countries, territories or areas with...",geospatial distribution,health,unclear,global,specific date (24 March 2020),counts,The figure displays a world map indicating cou...
2,Annex 10: Country at a Glance\nWEST BANK AND G...,key economic ratios and demographic indicators,"poverty and social conditions, economic develo...",general population,West Bank and Gaza,single year (1997),"counts, percentages, USD billions",The snapshot reports on various socio-economic...
3,Project Development Objective Indicators,performance indicators,refugee management,refugees,Pakistan,unclear,"percentages, counts",The table outlines project development objecti...
4,Annex 6\nEl Nino Emergency Road Repair Project...,administrative counts,infrastructure rehabilitation,unclear,Uganda,specific dates and planned timelines,"US dollars, months, specific dates",The snapshot contains a project budget and sch...
5,Table C: Allocation of Loan Proceeds,financial allocation,infrastructure development,unclear,unclear,unclear,"US$ million, percentage",The table reports the allocation of loan proce...
6,Component,budget allocation,community development,unclear,Rwanda,unclear,US$ million,The table reports the budget allocation for va...
7,none,administrative counts,infrastructure repair,unclear,Albania,unclear,monetary values (in currency),The table reports various road repair projects...
8,Project Cost and Financing Plan,financial reporting,infrastructure development,unclear,Croatia,multi-year trend,DEM million,The snapshot presents data on project costs an...
9,Burundi at a glance,statistical data,socio-economic indicators,unclear,Burundi,single year (1997) and historical data from 19...,"various (millions, percentages, ratios, US dol...",The snapshot provides various socio-economic i...
10,Table 3: Procurement of major Goods and Works ...,administrative counts,education,unclear,Lebanon,specific project duration,"USD, months",The table reports on the procurement of major ...
11,Jordan STATEMENT OF IFC's Committed and Disbur...,administrative counts,infrastructure financing,companies,Jordan,single date,millions of USD,The table reports on the committed and disburs...
12,Beneficiaries with access to basic services in...,monitoring indicators,basic services,beneficiaries,unclear,unclear,counts,The table reports the baseline and end target ...
13,1 : FIGA is reformed in a manner satisfactory ...,administrative counts,livelihoods,MSMEs,Burundi,unclear,USD,The table reports on the reform status of FIGA...
14,STATEMENT OF IFC's Committed and Disbursed Por...,financial reporting,economic investment,companies,Tajikistan,specific date,millions of US dollars,The table reports the committed and disbursed ...
15,1. Project components (see Annex 2 for a detai...,administrative counts,"infrastructure, social services","local government units (LGUs), local contracto...",West Bank and Gaza,unclear,"USD million (US$M), percentages",The table presents the indicative costs and fi...
16,TABLE A: PROJECT COSTS BY PROCUREMENT ARRANGEM...,administrative counts,project costs,unclear,Burundi,unclear,million US dollars,The table reports the costs associated with va...
17,Enhanced production and income generation amon...,counts,livelihoods,"farmers, including female farmers",unclear,multi-year trend,Number,The table reports the number of farmers and fe...
18,"IDA Resources (US$, Millions)",financial allocations,funding mechanisms,unclear,Djibouti,multi-year trend,millions of USD,This table reports financial allocations from ...
19,Uganda STATEMENT OF IFC's Committed and Disbur...,financial reporting,infrastructure financing,companies,Uganda,single year,US dollar millions,The table reports the committed and disbursed ...
20,Project Financing Data,project financing details,"community development, social assistance",unclear,Burundi,multi-year trend,US dollars,The table presents financing details for the S...
21,Table C: Allocation of Loan Proceeds,financial allocation,infrastructure and environmental protection,unclear,Croatia,unclear,US $million,The table details the allocation of loan proce...
22,"Annex 4, Table D: Allocation of Loan Proceeds",financial allocations,education,unclear,Tajikistan,unclear,US$ million,The table presents the allocation of loan proc...
23,"Annex 4, Table C: Summary of Procurement Activ...",administrative counts,education,unclear,Tajikistan,unclear,monetary values (million USD),The table summarizes procurement thresholds fo...
24,1. Project components (see Annex 2 for a detai...,cost analysis,municipal environmental infrastructure,unclear,Croatia,unclear,million DEM,The table reports the costs associated with di...
25,Category\nAmount of the Grant Allocated (expre...,financial allocations,education,unclear,Lebanon,unclear,"USD, percentage",The table reports the amount allocated for var...
26,PRICES and GOVERNMENT FINANCE,statistical data,economics,country-level,Albania,"multiple years (1977, 1987, 1997, 1998)","US$ millions, percentages",The snapshot presents economic indicators for ...
27,4.7 موجز التحليلي (بالدولار الأمريكي),projections,economic analysis,unclear,Djibouti,multi-year trend,thousands of USD,The table presents financial projections relat...
28,Team,administrative counts,education,unclear,unclear,annual,"number of staff weeks, number of trips",The table outlines various expertise needed fo...
29,PDO Indicators by PDO Outcomes,monitoring indicators,social assistance,beneficiaries,unclear,baseline and closing period,number,"This table reports on project beneficiaries, i..."
30,Tajikistan,administrative counts,economics,unclear,country-level,multi-year trend,"US$ millions, percentages",The data reports on various economic indicator...
31,Microcredentials firm contracted\nMicrocredent...,progress indicators,education,secondary education students,Costa Rica,unclear,counts / percentages,The table reports on milestones related to a m...
32,JORDAN COMMUNITY INFRASTRUCTURE PROJECT LOCATI...,administrative counts,infrastructure,squatter settlements,"Greater Amman, Jordan",unclear,geographic locations,The snapshot depicts a map showing the locatio...
33,Table 5: Project Cost and Financing,administrative counts,health,unclear,Iraq,unclear,US$ million,The table outlines the costs and financing sou...
34,Table 1: Implementation Support Table,resource allocation and operational planning,education,unclear,Lebanon,multi-year plan (first twelve months and 12-48...,US$,"The table outlines the timing, focus areas, sk..."
35,Project Costs and Financing,budget allocation,urban development,unclear,West Bank and Gaza,unclear,USD million,The table outlines the financial requirements ...
36,Annex 5: Financial Summary\nALBANIA: Emergency...,financial summary,infrastructure repair,unclear,Albania,7 years indicated,US$ million,The table summarizes the required project cost...
37,Intermediate Indicators by Components,baseline and target indicators,socio-economic inclusion,refugees and host communities,Rwanda,baseline (2025) and closing period (2030),"number, percentage, kilometers",The table reports intermediate indicators for ...