In [1]:
import glob
import pandas as pd

# Load files

In [2]:
files = glob.glob("data/results_*.jsonl")
files

['data/results_refugee.jsonl',
 'data/results_unhcr.jsonl',
 'data/results_prwp.jsonl']

In [3]:
df = pd.concat([pd.read_json(x, lines=True) for x in files]).reset_index(drop=True)
df

,snapshot_id,source,model,raw_output,usage,cost,status,incomplete_details,parsed_output,error
0,027_Jordan-Emergency-Food-Security-Project_fig...,refugee,gpt-5.5,"{""fields"":[{""metadata_field"":""figure_title"",""o...","{'input_tokens': 7168, 'input_tokens_details':...","{'input_tokens': 7168, 'output_tokens': 2431, ...",completed,NaN,"{'fields': [{'metadata_field': 'figure_title',...",NaN
1,054_Sudan-Basic-Education-Emergency-Support-Pr...,refugee,gpt-5.5,"{""fields"":[{""metadata_field"":""figure_title"",""o...","{'input_tokens': 13799, 'input_tokens_details'...","{'input_tokens': 13799, 'output_tokens': 1576,...",completed,NaN,"{'fields': [{'metadata_field': 'figure_title',...",NaN
2,134_PAD7340ARABIC00n0220020140Arabic01_figure_...,refugee,gpt-5.5,"{""fields"":[{""metadata_field"":""figure_title"",""o...","{'input_tokens': 13286, 'input_tokens_details'...","{'input_tokens': 13286, 'output_tokens': 1460,...",completed,NaN,"{'fields': [{'metadata_field': 'figure_title',...",NaN
3,004_BOSIB-87c444de-4797-4bf9-b654-4932a7fb0112...,refugee,gpt-5.5,"{""fields"":[{""metadata_field"":""figure_title"",""o...","{'input_tokens': 8299, 'input_tokens_details':...","{'input_tokens': 8299, 'output_tokens': 2116, ...",completed,NaN,"{'fields': [{'metadata_field': 'figure_title',...",NaN
4,202_multi0page_figure_000.png,refugee,gpt-5.5,"{""fields"":[{""metadata_field"":""geographic_scope...","{'input_tokens': 12161, 'input_tokens_details'...","{'input_tokens': 12161, 'output_tokens': 2134,...",completed,NaN,{'fields': [{'metadata_field': 'geographic_sco...,NaN
...,...,...,...,...,...,...,...,...,...,...
205,document_8886604_table_005.png,prwp,gpt-5.5,"{""fields"":[{""metadata_field"":""table_title"",""ob...","{'input_tokens': 12587, 'input_tokens_details'...","{'input_tokens': 12587, 'output_tokens': 1475,...",completed,NaN,"{'fields': [{'metadata_field': 'table_title', ...",NaN
206,document_6284707_table_004.png,prwp,gpt-5.5,"{""fields"":[{""metadata_field"":""table_panel_titl...","{'input_tokens': 8238, 'input_tokens_details':...","{'input_tokens': 8238, 'output_tokens': 3145, ...",completed,NaN,{'fields': [{'metadata_field': 'table_panel_ti...,NaN
207,document_7095002_table_002.png,prwp,gpt-5.5,"{""fields"":[{""metadata_field"":""table_title"",""ob...","{'input_tokens': 9890, 'input_tokens_details':...","{'input_tokens': 9890, 'output_tokens': 1640, ...",completed,NaN,"{'fields': [{'metadata_field': 'table_title', ...",NaN
208,document_7063025_table_001.png,prwp,gpt-5.5,"{""fields"":[{""metadata_field"":""table_title"",""ob...","{'input_tokens': 8278, 'input_tokens_details':...","{'input_tokens': 8278, 'output_tokens': 1525, ...",completed,NaN,"{'fields': [{'metadata_field': 'table_title', ...",NaN
209,document_10395051_table_002.png,prwp,gpt-5.5,"{""fields"":[{""metadata_field"":""table_title"",""ob...","{'input_tokens': 10925, 'input_tokens_details'...","{'input_tokens': 10925, 'output_tokens': 1579,...",completed,NaN,"{'fields': [{'metadata_field': 'table_title', ...",NaN

In [4]:
# df = df[df["model"] == "gpt-5.4-mini"].copy()

# Type

In [5]:
df["type"] = df["snapshot_id"].apply(lambda x: x.split("_")[-2])
df.groupby(["source", "type"]).agg(
    count=("source", "count"),
)

                count
source  type
prwp    figure     35
        table      35
refugee figure     35
        table      35
unhcr   figure     35
        table      35

# Cost

In [6]:
df = df.reset_index(drop=True).join(pd.json_normalize(df["cost"]))

total = df["total_cost_usd"].sum()
mean = df["total_cost_usd"].mean()
std = df["total_cost_usd"].std()

print(f"Total cost: ${total:.2f}")
print(f"Ave cost per snapshot: ${mean:.4f}")
print(f"Std dev: ${std:.4f}")

Total cost: $19.75
Ave cost per snapshot: $0.0940
Std dev: $0.0290

In [7]:
df.groupby(["source", "model"]).agg(
    count=("source", "count"),
    total_cost_usd=("total_cost_usd", "sum"),
    ave_cost_usd=("total_cost_usd", "mean"),
    std_cost_usd=("total_cost_usd", "std"),
)

                 count  total_cost_usd  ave_cost_usd  std_cost_usd
source  model
prwp    gpt-5.5     70        7.066405      0.100949      0.017077
refugee gpt-5.5     70        8.094555      0.115636      0.024120
unhcr   gpt-5.5     70        4.587440      0.065535      0.018193

# Output tokens

In [8]:
total = df["output_tokens"].sum()
mean = df["output_tokens"].mean()
std = df["output_tokens"].std()

print(f"Total output tokens: {total}")
print(f"Ave output token per snapshot: {mean}")
print(f"Std dev: {std:.2f}")

Total output tokens: 350948
Ave output token per snapshot: 1671.1809523809525
Std dev: 405.15

In [9]:
df.groupby(["source", "model"]).agg(
    count=("source", "count"),
    total_output_tokens=("output_tokens", "sum"),
    ave_output_tokens=("output_tokens", "mean"),
    std_output_tokens=("output_tokens", "std"),
)

,,count,total_output_tokens,ave_output_tokens,std_output_tokens
source,model,,,,
prwp,gpt-5.5,70,119324,1704.628571,417.413123
refugee,gpt-5.5,70,124846,1783.514286,429.495786
unhcr,gpt-5.5,70,106778,1525.400000,320.939942

# Raw output

In [10]:
# df

In [11]:
# df.loc[0, "raw_output"]

# Parsed output

In [12]:
# df.loc[0, "parsed_output"]["fields"]